PUT /apps/thor/versions/1.0.0

{
    "schema": {
        "type": "object",
        "properties": {
            "nickname": {
                "type": "string"
            }
        },
        "required": [
            "nickname"
        ]
    },
    "configuration": {
        "nickname": "Thor"
    }
}

###
GET /apps/thor/versions/1.0.0/configuration

###
PUT /apps/thor/versions/1.0.0/configuration

{
    "nickname": "Tornado"
}

###
PUT /apps/thor/versions/1.0.1

{
    "schema": {
        "type": "object",
        "properties": {
            "nickname": {
                "type": "string"
            },
            "age" : {
                "type": "decimal"
            }
        },
        "required": [
            "nickname",
            "age"
        ]
    },
    "configuration": {
        "nickname": "Thor",
        "age": 0.8
    }
}

###
GET /apps/thor/versions/1.0.1/configuration

###
GET /apps/thor/versions/latest/configuration

###
GET /apps/thor/versions/latest