<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Confi</RootNamespace>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Persic.Mongo" Version="2025.107.107.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\protocol\Confi.Manager.Protocol.csproj" />
  </ItemGroup>

</Project>
