on:
  push:
    paths:
      - 'dotnet/core/**'
      - '.github/workflows/core-nuget.yml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: dotnet/core/Confi
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}