on:
  push:
    paths:
      - 'dotnet/ef/**'
      - '.github/workflows/ef-nuget.yml'

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: dotnet/ef/Confi.EF
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}